// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemporaryLinks.Addon.Data;

#nullable disable

namespace TemporaryLinks.Addon.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251213105345_AddActionTemplates")]
    partial class AddActionTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("TemporaryLinks.Addon.Models.ActionTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("ActionTemplates");
                });

            modelBuilder.Entity("TemporaryLinks.Addon.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Info")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("TemporaryLinks.Addon.Models.LinkSmsAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SmsSent")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TemporaryLinkId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TwilioMessageSid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TemporaryLinkId");

                    b.HasIndex("Timestamp");

                    b.ToTable("LinkSmsAudits");
                });

            modelBuilder.Entity("TemporaryLinks.Addon.Models.LinkUsageAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TemporaryLinkId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TemporaryLinkId");

                    b.HasIndex("Timestamp");

                    b.ToTable("LinkUsageAudits");
                });

            modelBuilder.Entity("TemporaryLinks.Addon.Models.TemporaryLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudhookId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudhookUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxUses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ValidFrom")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ValidUntil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebhookId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("ValidUntil");

                    b.ToTable("TemporaryLinks");
                });

            modelBuilder.Entity("TemporaryLinks.Addon.Models.LinkSmsAudit", b =>
                {
                    b.HasOne("TemporaryLinks.Addon.Models.TemporaryLink", "TemporaryLink")
                        .WithMany("SmsEntries")
                        .HasForeignKey("TemporaryLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemporaryLink");
                });

            modelBuilder.Entity("TemporaryLinks.Addon.Models.LinkUsageAudit", b =>
                {
                    b.HasOne("TemporaryLinks.Addon.Models.TemporaryLink", "TemporaryLink")
                        .WithMany("AuditEntries")
                        .HasForeignKey("TemporaryLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemporaryLink");
                });

            modelBuilder.Entity("TemporaryLinks.Addon.Models.TemporaryLink", b =>
                {
                    b.Navigation("AuditEntries");

                    b.Navigation("SmsEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
